// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmqN9h87Cay6exAY3mtjZOHQlZZ586TWg',
    appId: '1:344091249752:web:f7383f32a9a1b0525b4e2d',
    messagingSenderId: '344091249752',
    projectId: 'crypto-wallet-4de58',
    authDomain: 'crypto-wallet-4de58.firebaseapp.com',
    storageBucket: 'crypto-wallet-4de58.firebasestorage.app',
    measurementId: 'G-HCPL2TBN8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP3Xe6U0fEyPTmTSPbdixZBfwgOAIQ1A8',
    appId: '1:344091249752:android:35996f0fe17fdf545b4e2d',
    messagingSenderId: '344091249752',
    projectId: 'crypto-wallet-4de58',
    storageBucket: 'crypto-wallet-4de58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGnWDtpeScVenKmVwTimbHXTKDV4ywhcE',
    appId: '1:344091249752:ios:feef654497a219365b4e2d',
    messagingSenderId: '344091249752',
    projectId: 'crypto-wallet-4de58',
    storageBucket: 'crypto-wallet-4de58.firebasestorage.app',
    iosBundleId: 'com.example.cryptoWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGnWDtpeScVenKmVwTimbHXTKDV4ywhcE',
    appId: '1:344091249752:ios:feef654497a219365b4e2d',
    messagingSenderId: '344091249752',
    projectId: 'crypto-wallet-4de58',
    storageBucket: 'crypto-wallet-4de58.firebasestorage.app',
    iosBundleId: 'com.example.cryptoWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmqN9h87Cay6exAY3mtjZOHQlZZ586TWg',
    appId: '1:344091249752:web:caa8cf7c176411555b4e2d',
    messagingSenderId: '344091249752',
    projectId: 'crypto-wallet-4de58',
    authDomain: 'crypto-wallet-4de58.firebaseapp.com',
    storageBucket: 'crypto-wallet-4de58.firebasestorage.app',
    measurementId: 'G-26ETYZZF63',
  );
}
